# This is a basic workflow to help you get started with Actions

name: convert_diagram_to_img

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Convert test file to png image
      uses: ./
      with:
        quality: 100
        scale: 1.0
        src: test/test.drawio
        dest: test.png
    - name: Convert test file to jpeg image
      uses: ./
      with:
        quality: 100
        scale: 1.0
        src: test/test.drawio
        dest: test.jpeg
    - name: Convert test file to svg image
      uses: ./
      with:
        scale: 1.0
        src: test/test.drawio
        dest: test.svg
    - name: Convert test file to pdf
      uses: ./
      with:
        scale: 1.0
        src: test/test.drawio
        dest: test.pdf
    - name: Upload images as artifacts
      uses: actions/upload-artifact@v1
      with:
        name: png
        path: test.png
    - uses: actions/upload-artifact@v1
      with:
        name: jpeg
        path: test.jpeg
    - uses: actions/upload-artifact@v1
      with:
        name: svg
        path: test.svg
    - uses: actions/upload-artifact@v1
      with:
        name: pdf
        path: test.pdf
