# This is a basic workflow to help you get started with Actions

name: convert_diagram_to_img

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: echo
      run: pwd
    
    - name: ls
      run: ls
    - name: Convert test file to png image
      uses: Burnett01/actions-drawio@1.2
      with:
        src: test.drawio
        dest: test.png
    - name: Upload images as artifacts
      uses: actions/upload-artifact@v1
      with:
        name: png
        path: test.png
